name: "Terraform Infrastructure Deployment"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

      - name: Configure Terraform Backend
        run: |
          cat > backend.tf << EOF
          terraform {
            backend "gcs" {
              bucket = "terraform-state-${GITHUB_REPOSITORY_OWNER}"
              prefix = "terraform/state"
            }
          }
          EOF
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          export PROJECT_ID=$(cat /tmp/gcp-key.json | jq -r '.project_id')
          gcloud config set project $PROJECT_ID
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Create State Bucket if Not Exists
        run: |
          gsutil ls -b gs://terraform-state-${GITHUB_REPOSITORY_OWNER} || \
          gsutil mb -l us-central1 gs://terraform-state-${GITHUB_REPOSITORY_OWNER}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Enable Versioning on State Bucket
        run: gsutil versioning set on gs://terraform-state-${GITHUB_REPOSITORY_OWNER}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Create and Select Workspace
        run: |
          # Create a unique workspace name using timestamp and commit SHA
          WORKSPACE_NAME="deploy-$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}"
          terraform workspace new $WORKSPACE_NAME || terraform workspace select $WORKSPACE_NAME
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Import Existing Resources
        run: |
          # Import BigQuery dataset with retry logic
          for i in {1..3}; do
            if terraform import google_bigquery_dataset.payroll_dataset ${PROJECT_ID}:payroll_analytics; then
              break
            fi
            echo "Import attempt $i failed, waiting before retry..."
            sleep 5
          done || true

          # Import BigQuery tables with retry logic
          for table in cpa_firms businesses employees pay_periods payroll_records deductions taxes employee_payroll_summary; do
            for i in {1..3}; do
              if terraform import google_bigquery_table.$table ${PROJECT_ID}.payroll_analytics.$table; then
                break
              fi
              echo "Import attempt $i failed for table $table, waiting before retry..."
              sleep 5
            done || true
          done
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -out=tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          terraform apply -auto-approve tfplan || {
            echo "Terraform apply failed. Initiating rollback..."
            terraform destroy -auto-approve \
              -var="db_password=${{ secrets.DB_PASSWORD }}"
            exit 1
          }
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Output Infrastructure Details
        if: success()
        run: |
          echo "Cloud SQL Instance: $(terraform output -raw instance_connection_name)"
          echo "Database Name: $(terraform output -raw database_name)"
          echo "BigQuery Dataset: $(terraform output -raw bigquery_dataset_id)"
          echo "Datastream ID: $(terraform output -raw datastream_stream_id)"

      - name: Cleanup on Failure
        if: failure()
        run: |
          echo "Cleaning up resources..."
          terraform destroy -auto-approve \
            -var="db_password=${{ secrets.DB_PASSWORD }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
